<?php

namespace InTradeSys\eBay\bulkDataExchange;

/*
 * This class was generated from a WSDL file from November 27, 2020, 4:15 pm.
 * Executed by globalsync.
 * Provided and maintained by:
 *
 *  InTradeSys GmbH
 *  Dillenburger Str. 75
 *  D-51105 Cologne
 *  ---
 *  https://www.intradesys.com
 */

/**
 * Type defining the root container of the
 * abortJob
 * response. The response includes the standard output fields like
 * ack
 * ,
 * timestamp
 * ,
 * version
 * , and any errors/warnings that are generated by the request to abort a job.
 **/
class AbortJobResponse extends EbatNsBulkDataExchange_Response
{
    const TAG = 'AbortJobResponse';
    const NAME = 'AbortJobResponse';
    const XMLNS = 'http://www.ebay.com/marketplace/services';

    
    /**
     * Register child elements and attributes
     */
    public static function _register()
    {
        self::assignElements([], parent::NAME);
        self::assignAttributes([]);
    }

}

AbortJobResponse::_register();
